# Site settings
title: apiman Blog | Open Source API Management
email: apiman-user@lists.jboss.org
description: > # this means to ignore newlines until "baseurl:"
  The apiman project brings an open source development methodology to
  API Management, coupling a rich API design & configuration layer with
  a blazingly fast runtime.  This is the official apiman blog, where
  we discuss....whatever we're thinking about!
baseurl: "/blog"
url: "http://apiman.io" # the base hostname & protocol for your site
twitter_username: apiman_io
github_username: apiman
timezone: America/New_York

# Build settings
markdown: kramdown

kramdown:
   input: GFM
   hard_wrap: false

destination: ../blog
excerpt_separator: <!--more-->

gems:
  - jekyll-sitemap
  - jekyll-asciidoc
  - asciidoctor-diagram

asciidoc: asciidoctor
asciidoc_ext: asciidoc,adoc,ad
asciidoctor:
  attributes:
    - imagesdir=/blog/images/generated
    - imagesoutdir=/images/generated
    - icons=font
    - source-highlighter=coderay
    - idprefix=
    - idseparator=-
    - linkattrs

sass:
  sass_dir: _sass